export const miniMenuBardata = [
  {
    id: 1,
    name: "menu",
    textimg: "M",
    totalItems: "120",
  },

  {
    id: 2,
    name: "Breads",
    textimg: "B",
    totalItems: "20",
  },

  {
    id: 3,
    name: "Cakes",
    textimg: "C",
    totalItems: "20",
  },

  {
    id: 4,
    name: "Donutes",
    textimg: "D",
    totalItems: "20",
  },

  {
    id: 5,
    name: "Pastries",
    textimg: "P",
    totalItems: "20",
  },
  {
    id: 6,
    name: "Sandwich",
    textimg: "S",
    totalItems: "20",
  },

  {
    id: 7,
    name: "Candy",
    textimg: "S",
    totalItems: "20",
  },

  {
    id: 8,
    name: "Drinks",
    textimg: "S",
    totalItems: "20",
  },
];

export const Menudata = [
  {
    id: 1,
    name: "Veg Sandwich",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Sandwich",
    price: 6.49,
  },
  {
    id: 2,
    name: "Chocolate Cake",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Cake",
    price: 8.99,
  },
  {
    id: 3,
    name: "Strawberry Pastry",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Pastry",
    price: 4.99,
  },
  {
    id: 4,
    name: "Garlic Bread",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Bread",
    price: 3.49,
  },
  {
    id: 5,
    name: "Glazed Donut",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Donut",
    price: 2.99,
  },
  {
    id: 6,
    name: "Chicken Sandwich",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Sandwich",
    price: 7.49,
  },
  {
    id: 7,
    name: "Cheese Croissant",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Pastry",
    price: 5.49,
  },
  {
    id: 8,
    name: "Red Velvet Cake",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Cake",
    price: 9.99,
  },
  {
    id: 9,
    name: "Blueberry Muffin",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Pastry",
    price: 4.79,
  },
  {
    id: 10,
    name: "Bagel with Cream Cheese",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Bread",
    price: 3.99,
  },
  {
    id: 11,
    name: "Chocolate Donut",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Donut",
    price: 3.29,
  },
  {
    id: 12,
    name: "Egg Sandwich",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Sandwich",
    price: 6.99,
  },
  {
    id: 13,
    name: "French Baguette",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Bread",
    price: 4.59,
  },
  {
    id: 14,
    name: "Pumpkin Pie",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Pastry",
    price: 5.99,
  },
  {
    id: 15,
    name: "Carrot Cake",
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Cake",
    price: 7.89,
  },
];

// export const Menudataold= [
//   {
//     id: 1,
//     name: "Veg Sandwich",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Sandwich",
//     price: 6.49,
//   },
//   {
//     id: 2,
//     name: "Chocolate Cake",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Cake",
//     price: 8.99,
//   },
//   {
//     id: 3,
//     name: "Strawberry Pastry",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Pastry",
//     price: 4.99,
//   },
//   {
//     id: 4,
//     name: "Garlic Bread",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Bread",
//     price: 3.49,
//   },
//   {
//     id: 5,
//     name: "Glazed Donut",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Donut",
//     price: 2.99,
//   },
//   {
//     id: 6,
//     name: "Chicken Sandwich",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Sandwich",
//     price: 7.49,
//   },
//   {
//     id: 7,
//     name: "Cheese Croissant",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Pastry",
//     price: 5.49,
//   },
//   {
//     id: 8,
//     name: "Red Velvet Cake",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Cake",
//     price: 9.99,
//   },
//   {
//     id: 9,
//     name: "Blueberry Muffin",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Pastry",
//     price: 4.79,
//   },
//   {
//     id: 10,
//     name: "Bagel with Cream Cheese",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Bread",
//     price: 3.99,
//   },
//   {
//     id: 11,
//     name: "Chocolate Donut",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Donut",
//     price: 3.29,
//   },
//   {
//     id: 12,
//     name: "Egg Sandwich",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Sandwich",
//     price: 6.99,
//   },
//   {
//     id: 13,
//     name: "French Baguette",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Bread",
//     price: 4.59,
//   },
//   {
//     id: 14,
//     name: "Pumpkin Pie",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Pastry",
//     price: 5.99,
//   },
//   {
//     id: 15,
//     name: "Carrot Cake",
//     imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
//     itemType: "Cake",
//     price: 7.89,
//   },

  
// ]

// export const ItemLists=[

//   {
//     id: 1,
//     name: "Veg Sandwich",
//     imgSrc: "https://placehold.co/120x80/FAFAFA/000000.svg",
//     itemType: "Sandwich",
//     price: "6.49",
//     quantity: "1",
//   },
//   {
//     id: 2,
//     name: "Chocolate Cake",
//     imgSrc: "https://placehold.co/120x80/FAFAFA/000000.svg",
//     itemType: "Cake",
//     price: "8.99",
//     quantity: "3",
//   },
//   {
//     id: 3,
//     name: "Strawberry Pastry",
//     imgSrc: "https://placehold.co/120x80/FAFAFA/000000.svg",
//     itemType: "Pastry",
//     price: "4.99",
//     quantity: "2",
//   },
//   {
//     id: 4,
//     name: "Garlic Bread",
//     imgSrc: "https://placehold.co/120x80/FAFAFA/000000.svg",
//     itemType: "Bread",
//     price: "3.49",
//     quantity: "3",
//   },
//   {
//     id: 5,
//     name: "Glazed Donut",
//     imgSrc: "https://placehold.co/120x80/FAFAFA/000000.svg",
//     itemType: "Donut",
//     price: "2.99",
//     quantity: "2",
//   },
//   {
//     id: 6,
//     name: "Chicken Sandwich",
//     imgSrc: "https://placehold.co/120x80/FAFAFA/000000.svg",
//     itemType: "Sandwich",
//     price: "7.49",
//     quantity: "1",
//   },
//   {
//     id: 7,
//     name: "Cheese Croissant",
//     imgSrc: "https://placehold.co/120x80/FAFAFA/000000.svg",
//     itemType: "Pastry",
//     price: "5.49",
//     quantity: "4",
//   },
// ]

// lib/data.ts

export const categories = [
  {
    id: 1,
    name: "Burger",
    slug: "burger",
    icon: "Utensils", // Lucide Icon Name
    color: "bg-orange-100 text-orange-600",
    count: 120,
    imageurl: "asd",
  },
  {
    id: 2,
    name: "Pizza",
    slug: "pizza",
    icon: "Pizza",
    color: "bg-red-100 text-red-600",
    count: 20,
    imageurl: "asd",
  },
  {
    id: 3,
    name: "Drinks",
    slug: "drinks",
    icon: "CupSoda",
    color: "bg-blue-100 text-blue-600",
    count: 20,
    imageurl: "asd",
  },
  {
    id: 4,
    name: "Dessert",
    slug: "dessert",
    icon: "IceCream",
    color: "bg-pink-100 text-pink-600",
    count: 20,
    imageurl: "asd",
  },
  {
    id: 5,
    name: "Sides",
    slug: "sides",
    icon: "FrenchFries",
    color: "bg-yellow-100 text-yellow-600",
    count: 20,
    imageurl: "asd",
  },
  {
    id: 6,
    name: "Saleds",
    slug: "Saleds",
    icon: "FrenchFries",
    color: "bg-yellow-100 text-yellow-600",
    count: 20,
    imageurl: "asd",
  },
];

export const products = [
  // --- BURGERS (Category 1) ---
  {
    id: 101,
    categoryId: 1,
    name: "Classic Cheeseburger",
    description: "Beef patty, cheddar, lettuce, tomato, house sauce.",
    price: 8.99,
    costPrice: 3.5,
    stock: 45,
    sku: "BGR-CLS-001",
    image: "/images/burger-classic.jpg",
  },
  {
    id: 102,
    categoryId: 1,
    name: "Double Bacon Smash",
    description: "Two smashed patties, crispy bacon, american cheese.",
    price: 12.99,
    costPrice: 5.2,
    stock: 20,
    sku: "BGR-DBL-002",
    image: "/images/burger-bacon.jpg",
  },
  {
    id: 103,
    categoryId: 1,
    name: "Spicy Chicken Sandwich",
    description: "Fried chicken breast, pepper jack, jalapeños.",
    price: 9.49,
    costPrice: 4.0,
    stock: 30,
    sku: "BGR-CHK-003",
    image: "/images/burger-chicken.jpg",
  },

  // --- PIZZA (Category 2) ---
  {
    id: 201,
    categoryId: 2,
    name: "Margherita Slice",
    description: "Tomato sauce, fresh mozzarella, basil.",
    price: 4.5,
    costPrice: 1.2,
    stock: 15,
    sku: "PZA-MAR-001",
    image: "/images/pizza-margherita.jpg",
  },
  {
    id: 202,
    categoryId: 2,
    name: "Pepperoni Whole",
    description: "18-inch NY Style pepperoni pizza.",
    price: 24.0,
    costPrice: 8.0,
    stock: 10,
    sku: "PZA-PEP-002",
    image: "/images/pizza-pepperoni.jpg",
  },

  // --- DRINKS (Category 3) ---
  {
    id: 301,
    categoryId: 3,
    name: "Cola Zero",
    description: "500ml bottle.",
    price: 2.5,
    costPrice: 0.8,
    stock: 100,
    sku: "DRK-COL-001",
    image: "/images/drink-cola.jpg",
  },
  {
    id: 302,
    categoryId: 3,
    name: "Iced Latte",
    description: "Espresso with cold milk and ice.",
    price: 4.5,
    costPrice: 1.5,
    stock: 50,
    sku: "DRK-COF-002",
    image: "/images/drink-latte.jpg",
  },
  {
    id: 303,
    categoryId: 3,
    name: "Fresh Orange Juice",
    description: "Cold pressed daily.",
    price: 5.99,
    costPrice: 2.0,
    stock: 25,
    sku: "DRK-ORJ-003",
    image: "/images/drink-orange.jpg",
  },

  // --- DESSERTS (Category 4) ---
  {
    id: 401,
    categoryId: 4,
    name: "New York Cheesecake",
    description: "Classic slice with strawberry drizzle.",
    price: 6.5,
    costPrice: 2.5,
    stock: 12,
    sku: "DST-CHS-001",
    image: "/images/dessert-cheese.jpg",
  },
  {
    id: 402,
    categoryId: 4,
    name: "Chocolate Fudge Brownie",
    description: "Served warm with vanilla ice cream.",
    price: 5.99,
    costPrice: 1.8,
    stock: 20,
    sku: "DST-BRW-002",
    image: "/images/dessert-brownie.jpg",
  },

  // --- SIDES (Category 5) ---
  {
    id: 501,
    categoryId: 5,
    name: "French Fries",
    description: "Crispy salted fries.",
    price: 3.99,
    costPrice: 0.5,
    stock: 200,
    sku: "SDS-FRI-001",
    image: "/images/side-fries.jpg",
  },
  {
    id: 502,
    categoryId: 5,
    name: "Onion Rings",
    description: "Battered and fried onion rings.",
    price: 4.5,
    costPrice: 0.8,
    stock: 80,
    sku: "SDS-ONI-002",
    image: "/images/side-rings.jpg",
  },
];

// Product data from backend API
export const apiProducts = [
  {
    id: "cmmabglnc00064wnn2hfphr0k",
    name: "Caesar Salad",
    price: 6.99,
    skuId: "SKU_SAL_015",
    isActive: true,
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Salads",
    category: { id: "cmlxzig4p00072onn3h1tv62c", name: "Salads" },
  },
  {
    id: "cmmabgloj000d4wnnnyna3f14",
    name: "Cappuccino",
    price: 3.99,
    skuId: "SKU_COF_022",
    isActive: true,
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Coffee",
    category: { id: "cmlxzig5i000d2onn4pwv7ys6", name: "Coffee" },
  },
  {
    id: "cmm2zpklw0002vcnn6kvasqb5",
    name: "Cheese Burger 5",
    price: 14.99,
    skuId: "SKU_BURG_012",
    isActive: true,
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Burgers",
    category: { id: "cmlxzig3z00022onnge0ybwh6", name: "Burgers" },
  },
  {
    id: "cmm2zmkt40000csnn2frez1jz",
    name: "Cheese Burger cre",
    price: 11.99,
    skuId: "SKU_BURG_003",
    isActive: true,
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Burgers",
    category: { id: "cmlxzig3z00022onnge0ybwh6", name: "Burgers" },
  },
  {
    id: "cmlxzig6n000h2onnj8j629np",
    name: "Chicken Burger",
    price: 5.49,
    skuId: "SKU_BURG_001",
    isActive: true,
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Burgers",
    category: { id: "cmlxzig3z00022onnge0ybwh6", name: "Burgers" },
  },
  {
    id: "cmmabglnw00094wnnqyk1g2dl",
    name: "Chicken Shawarma Wrap",
    price: 7.49,
    skuId: "SKU_WRP_018",
    isActive: true,
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Wraps",
    category: { id: "cmlxzig4z00092onnmmjvucfd", name: "Wraps" },
  },
  {
    id: "cmmabgln100044wnnl2x24dr9",
    name: "Chocolate Brownie",
    price: 4.49,
    skuId: "SKU_DST_013",
    isActive: true,
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Desserts",
    category: { id: "cmlxzig4g00052onnmqudyx2j", name: "Desserts" },
  },
  {
    id: "cmlxzkrac0000tsnnrkfi3f7x",
    name: "Cola",
    price: 1.99,
    skuId: "SKU_DRK_003",
    isActive: true,
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Drinks",
    category: { id: "cmlxzig4500032onnzx9n3ob1", name: "Drinks" },
  },
  {
    id: "cmlxzig6x000j2onntmk6cuvr",
    name: "Cola",
    price: 1.99,
    skuId: "SKU_DRK_001",
    isActive: true,
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Drinks",
    category: { id: "cmlxzig4500032onnzx9n3ob1", name: "Drinks" },
  },
  {
    id: "cmlxzig72000k2onnu0cc4euh",
    name: "French Fries",
    price: 2.99,
    skuId: "SKU_STR_001",
    isActive: true,
    imgSrc: "https://placehold.co/600x400/FAFAFA/000000.svg",
    itemType: "Starters",
    category: { id: "cmlxzig4b00042onnhv41ofwr", name: "Starters" },
  },
];
